apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: entities
  description: A collection of all the catalog entities
spec:
  targets:
    - ./all-janus-idp.yaml
    - ./groups.yaml
    - ./users.yaml
