apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: groups
  description: A collection of all groups
spec:
  targets:
    - ./groups/guests.yaml
    - ./groups/engineer.yaml
    - ./groups/janus-authors.yaml
    - ./groups/team-a.yaml
